name: Test

on:
  push:
    branches-ignore:
      - dev
  pull_request:
    branches-ignore:
      - dev

jobs:
  test-meta:
    name: Test metadata
    runs-on: ubuntu-latest

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run npm install for metadata
      run: npm install
      working-directory: packages/metadata

    - name: Test Metadata
      run: npm run test
      working-directory: packages/metadata

  testcafe:
    name: ${{ matrix.ARGS.project }} - ${{ matrix.ARGS.page }} - ${{ matrix.theme.type }}
    strategy:
      fail-fast: false
      matrix:
        theme: [
          { fullName: 'material.blue.light.compact', type: 'material', name: 'material.light' },
          { fullName: 'generic.light.compact', type: 'generic',  name: 'generic.light'},
        ]
        ARGS: [
          { project: 'angular', page: 'crm-contact-details' },
          { project: 'angular', page: 'crm-contact-list' },
          # { project: 'angular', page: 'planning-task-details' }, No selector for Toolbar item on mobile device(bug)
          { project: 'angular', page: 'planning-task-list' },
          { project: 'angular', page: 'planning-scheduler' },
          { project: 'angular', page: 'analytics-dashboard' },
          { project: 'angular', page: 'analytics-sales-report' },
          { project: 'angular', page: 'analytics-geography' },
          { project: 'angular', page: 'user-profile' },
          { project: 'angular', page: 'auth-pages' },
          { project: 'react', page: 'crm-contact-details' },
          { project: 'react', page: 'crm-contact-list' },
          # { project: 'react', page: 'planning-task-details' }, # Title width is different (screen width 400). Menu stays opened
          { project: 'react', page: 'planning-task-list' },
          { project: 'react', page: 'planning-scheduler' },
          { project: 'react', page: 'analytics-dashboard' },
          { project: 'react', page: 'auth-pages' },
          # { project: 'react', page: 'analytics-geography' }, # Menu contents disappear after item click (screen width 400)
          # { project: 'vue', page: 'crm-contact-details' }, No selector for Toolbar item on mobile device(bug)
          { project: 'react', page: 'analytics-sales-report' },
          { project: 'react', page: 'user-profile' },
          { project: 'vue', page: 'crm-contact-list' },
          # { project: 'vue', page: 'planning-task-details' }, # Title width is different (screen width 400)
          { project: 'vue', page: 'planning-task-list' },
          { project: 'vue', page: 'planning-scheduler' },
          { project: 'vue', page: 'analytics-dashboard' },
          { project: 'vue', page: 'analytics-sales-report' },
          { project: 'vue', page: 'analytics-geography' },
          { project: 'vue', page: 'auth-pages' },
          { project: 'vue', page: 'user-profile' },
        ]
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run npm install
      run: npm install --no-audit --no-fund

    - name: Set theme
      run: npm run set-theme -- ${{ matrix.theme.fullName }}

    - name: Build
      run: npm run build
      working-directory: packages/${{ matrix.ARGS.project }}

    - name: Start app
      run: npm run start-apps -- --project ${{ matrix.ARGS.project }} --theme ${{ matrix.theme.name }}
      working-directory: packages/testing

    - name: Run tests
      run: |
        all_args="--project ${{ matrix.ARGS.project }} --page ${{ matrix.ARGS.page }} --quarantineMode true  --theme ${{ matrix.theme.name }}"
        echo "$all_args"
        npm run test-testcafe -- $all_args
      working-directory: packages/testing

    - name: Copy screenshots artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: screenshots-${{ matrix.ARGS.project }}
        path: ${{ github.workspace }}/packages/testing/testing/artifacts/compared-screenshots/*
        if-no-files-found: ignore
