name: Test

on:
  push:
  pull_request:

jobs:
  test-meta:
    name: Test metadata
    runs-on: ubuntu-latest

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run npm install for metadata
      run: npm install
      working-directory: packages/metadata

    - name: Test Metadata
      run: npm run test
      working-directory: packages/metadata

  testcafe:
    name: ${{ matrix.ARGS.project }} - ${{ matrix.ARGS.page }} - ${{ matrix.theme.type }}
    strategy:
      fail-fast: false
      matrix:
        theme: [
          { fullName: 'material.blue.light.compact', type: 'material', name: 'material.light' },
          { fullName: 'generic.light.compact', type: 'generic',  name: 'generic.light'},
        ]
        ARGS: [
          { project: 'angular', page: 'crm-contact-details' },
          { project: 'angular', page: 'crm-contact-list' },
          # { project: 'angular', page: 'planning-task-details' }, No selector for Toolbar item on mobile device(bug)
          { project: 'angular', page: 'planning-task-list' },
          { project: 'angular', page: 'analytics-dashboard' },
          { project: 'angular', page: 'analytics-sales-report' },
          { project: 'angular', page: 'analytics-geography' },
          { project: 'angular', page: 'user-profile' },
          { project: 'angular', page: 'auth-forms' },
          { project: 'react', page: 'crm-contact-details' },
          { project: 'react', page: 'crm-contact-list' },
          # { project: 'react', page: 'planning-task-details' }, # Title width is different (screen width 400). Menu stays opened
          { project: 'react', page: 'planning-task-list' },
          { project: 'react', page: 'analytics-dashboard' },
          { project: 'react', page: 'auth-forms' },
          # { project: 'react', page: 'analytics-geography' }, # Menu contents disappear after item click (screen width 400)
          # { project: 'vue', page: 'crm-contact-details' }, No selector for Toolbar item on mobile device(bug)
          { project: 'react', page: 'analytics-sales-report' },
          { project: 'vue', page: 'crm-contact-list' },
          # { project: 'vue', page: 'planning-task-details' }, # Title width is different (screen width 400)
          { project: 'vue', page: 'planning-task-list' },
          { project: 'vue', page: 'analytics-dashboard' },
          { project: 'vue', page: 'analytics-sales-report' },
          { project: 'vue', page: 'analytics-geography' },
          { project: 'vue', page: 'auth-forms' },
          { project: 'vue', page: 'user-profile' },
        ]
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set NPM version
      run: npm i npm@7 -g

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run npm install
      run: npm install --no-audit --no-fund

    - name: Set theme
      run: npm run set-theme -- ${{ matrix.theme.fullName }}

    - name: Build
      run: npm run build
      working-directory: packages/${{ matrix.ARGS.project }}

    - name: Start app
      run: npm run start-apps -- --project ${{ matrix.ARGS.project }} --theme ${{ matrix.theme.name }}
      working-directory: packages/testing

    - name: Run tests
      run: |
        all_args="--project ${{ matrix.ARGS.project }} --page ${{ matrix.ARGS.page }} --quarantineMode true  --theme ${{ matrix.theme.name }}"
        echo "$all_args"
        export TESTCAFE_DASHBOARD_LAYOUT_TESTING_ENABLED=true
        export TESTCAFE_DASHBOARD_DEVEXTREME_TOKEN=eyJwcm9qZWN0SWQiOiI5ZjRlMTJjMC1kNmExLTQxZDEtYmE1OS0wZTI3OTE1N2QxZDAiLCJ0b2tlblNlY3JldCI6InQwQXh6bzFMczBDVE81VU95bzc2dkF2eE05Ym9pQ3JxajRCQUtyWm5la0EzYlp3SENOR3RoamFaWkhoa0xvRnJZM1lvV0ZlbEt2S2JyYjFkbEs5UFVoMmlGaG9aVlprdTU1NXhZWmhGQkQ0eWtBZENJWkJvdU9ZV1hDWlRkVi9sQUFxMVNlMkFtRkg5UkRXTTlTcEk0WmVOSkEwZnYwNUlDN3Q3UXFmZ3o2VUdYVDNvZDJHQ2RqclVKYnZrZ2ZmNjdRb3RNaXZuTG1CSmM4REdLelhhbmhobzMzVzE5U1Axd1NSNGR6d3ZWdHp2dGV2em5Da0cwR0dSc3Z3OWdQS214UHpFUGsreTJtMjlSZm92dGtuNGZtb0prRng1RzBSZ2o2WnhPSXBrUDZOMVZyWWhuTk9lc1VEQmVobzB1VGFjTlNwZFE0N2FVZCsydmM3Q3Y0QmtZQT09In0=
        export TESTCAFE_DASHBOARD_DEVEXTREME_URL=https://devextreme.resolve.sh
        export TESTCAFE_DASHBOARD_BUILD_ID=${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
        npm run test-testcafe -- $all_args
      working-directory: packages/testing

    - name: Copy screenshots artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: screenshots-${{ matrix.ARGS.project }}
        path: ${{ github.workspace }}/packages/testing/testing/artifacts/compared-screenshots/*
        if-no-files-found: ignore
